#Hugo configuration
title = "Video Player Test"
baseURL = "https:\/\/www.vpt.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758397"
subfolder = ""
